// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQt7B54qZ7w4mqzvjR2nkK1sxJCbpluU',
    appId: '1:344907963327:web:058bfb54c1296d8fc71f0a',
    messagingSenderId: '344907963327',
    projectId: 'biodatasaya-c11b3',
    authDomain: 'biodatasaya-c11b3.firebaseapp.com',
    storageBucket: 'biodatasaya-c11b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcZdMq6m3-AS_atFjEZTT36NK2xLbhUA',
    appId: '1:344907963327:android:663b6c6d6011619ec71f0a',
    messagingSenderId: '344907963327',
    projectId: 'biodatasaya-c11b3',
    storageBucket: 'biodatasaya-c11b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ORIRgEhYRMnKwps7vePFf80kN-5YY1s',
    appId: '1:344907963327:ios:3e9921b23b6d7144c71f0a',
    messagingSenderId: '344907963327',
    projectId: 'biodatasaya-c11b3',
    storageBucket: 'biodatasaya-c11b3.firebasestorage.app',
    iosBundleId: 'com.example.biodatasaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ORIRgEhYRMnKwps7vePFf80kN-5YY1s',
    appId: '1:344907963327:ios:3e9921b23b6d7144c71f0a',
    messagingSenderId: '344907963327',
    projectId: 'biodatasaya-c11b3',
    storageBucket: 'biodatasaya-c11b3.firebasestorage.app',
    iosBundleId: 'com.example.biodatasaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQt7B54qZ7w4mqzvjR2nkK1sxJCbpluU',
    appId: '1:344907963327:web:63d052351d2bdc35c71f0a',
    messagingSenderId: '344907963327',
    projectId: 'biodatasaya-c11b3',
    authDomain: 'biodatasaya-c11b3.firebaseapp.com',
    storageBucket: 'biodatasaya-c11b3.firebasestorage.app',
  );
}
